### ISSUE TITLE
My Business API v4.x Support?

### ISSUE THREAD

**Issue by msalzburg** [google/google-api-ruby-client#668] opened 2018-04-13 14:32 UTC
Since the Google My Business API v3.3 will be "sunsetted" on the 10th of may 2018 and this gem does not support any newer version yet - it would be nice to know if there is any attempt to release a version with My Business API v4.x support in time?

https://developers.google.com/my-business/content/sunset-dates

**Comment by mattwhisenhunt** [comment] 2018-04-13 16:53
Duplicate of #662

**Closed by mattwhisenhunt** 2018-04-13 16:53 UTC
