### ISSUE TITLE
Updating a file in DriveV3 errors: use PUT or POST instead of PATCH?

### ISSUE THREAD

**Issue by danbernier** [google/google-api-ruby-client#350] opened 2016-01-27 19:42 UTC
When calling `Google::Apis::DriveV3::DriveService#update_file`, I'm getting a `Google::Apis::ClientError`, whose `#status_code` is 405, and whose `#body` is "Bad HTTP method. Please use PUT or POST only."

I looked at the source, at [drive_v3/service.rb:872](https://github.com/google/google-api-ruby-client/blob/master/generated/google/apis/drive_v3/service.rb#L872), and it does indeed make either a simple command or an upload command with an HTTP method of `:patch` (excerpted here, for when the source changes):

```ruby
        def update_file(file_id, file_object = nil, ...
          if upload_source.nil?
            command =  make_simple_command(:patch, 'files/{fileId}', options)
          else
            command = make_upload_command(:patch, 'files/{fileId}', options)
            command.upload_source = upload_source
            command.upload_content_type = content_type
          end
          ...
```

**Comment by danbernier** [comment] 2016-01-27 19:51
I'm comfortable submitting a pull-request for this specific method, but a) I haven't signed a Contributor License Agreement yet, and b) more importantly, I'm not sure how many other methods in this class share this problem.

**Comment by danbernier** [comment] 2016-01-27 21:25
Oh, interesting! It looks like that whole file was auto-generated on 2015-12-14, in b7c94d83.

**Comment by sqrrrl** [comment] 2016-01-27 23:34
Yeah, the service interfaces are generated based on the API description.

This particular issue looks like a regression on the backend. It was supposed to have been fixed back in December.

**Comment by danbernier** [comment] 2016-01-28 20:23
Anything I can do to help? (I've now signed the Contributor License Agreement.)

**Comment by sqrrrl** [comment] 2016-01-28 22:28
I'm hoping they'll fix this quickly. There are a few different versions of the upload protocols, this and the objective-c client use a slightly newer one and are both affected by it. The other upload mechanisms were fixed back in December, just missed this one particular variation.

I can revert back to the older protocols if it doesn't look like it can be fixed anytime soon.

**Comment by sqrrrl** [comment] 2016-02-01 18:31
Looks like this will be fixed in ~ 2 weeks. Workaround for the moment is to use DriveV2 (functionally the same, v3 just cleans up a lot of rough edges and is a little simpler.)

**Comment by sqrrrl** [comment] 2016-02-16 20:30
Looks like this is fixed on the backend now.

**Closed by sqrrrl** 2016-02-16 20:30 UTC
