### ISSUE TITLE
certificate verify failed (Faraday::SSLError)

### ISSUE THREAD

**Issue by crypticsymbols** [google/google-api-ruby-client#253] opened 2015-07-10 14:23 UTC
OSX 10.10.3, Ruby 2.2.1p85, gem version 0.9.pre1

Full error:

/Users/username/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)
    from /Users/asmith/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in`block in connect'
    from /Users/asmith/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
    from /Users/asmith/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in`connect'
    from /Users/asmith/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
    from /Users/asmith/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:852:in`start'
    from /Users/asmith/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1375:in `request'
    from /Users/asmith/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in`perform_request'
    from /Users/asmith/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
    from /Users/asmith/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in`with_net_http_connection'
    from /Users/asmith/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
    from /Users/asmith/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.1/lib/faraday/request/url_encoded.rb:15:in`call'
    from /Users/asmith/.rvm/gems/ruby-2.2.1/gems/signet-0.6.1/lib/signet/oauth_2/client.rb:957:in `fetch_access_token'
    from /Users/asmith/.rvm/gems/ruby-2.2.1/gems/signet-0.6.1/lib/signet/oauth_2/client.rb:983:in`fetch_access_token!'
    from run.rb:17:in `<main>'

I am able to hotwire with this at the top:

require 'openssl'
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

...but that kinda sucks.

**Comment by sqrrrl** [comment] 2015-07-10 17:03
See #235 for a workaround. The cert bundle in this library has the correct roots. Setting an env variable will have signet pick it up.

I'll take a look at cleaning up signet so it picks up the correct roots by default next week.

**Comment by radar** [comment] 2015-07-21 01:05
I was getting this issue on my Mac too. `brew update` and then brew upgrade openssl` fixed it.

**Comment by radar** [comment] 2015-07-30 01:15
@sqrrrl I think this issue can be closed now as it can be fixed by updating `openssl`.

**Comment by asamasoma** [comment] 2015-08-06 17:59
@sqrrrl Updating `openssl` didn't solve this problem for me. I have to set `SSL_CERT_FILE` to the bundled `cacerts.pem` file.

**Comment by crypticsymbols** [comment] 2015-08-07 16:03
FWIW, this is what worked for me:

cert_path = Gem.loaded_specs['google-api-client'].full_gem_path+'/lib/cacerts.pem'
      ENV['SSL_CERT_FILE'] = cert_path

**Comment by Vanuan** [comment] 2015-09-24 20:36
Worth linking: https://github.com/rvm/rvm/issues/3330

**Comment by stevestofiel** [comment] 2015-10-09 21:21
> FWIW, this is what worked for me:

>cert_path = Gem.loaded_specs['google-api-client'].full_gem_path+'/lib/cacerts.pem'
>ENV['SSL_CERT_FILE'] = cert_path

Thanks crypticsymbols!  That worked for me as well on:

`ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14] on OS X 10.10.5)`
`google-api-client (0.8.6)`
`googleauth (0.4.2)`
`signet (0.6.1)`
`jwt (1.5.1)`

**Comment by schmierkov** [comment] 2015-10-15 11:29
@crypticsymbols thanks a lot, that works for me too!

**Comment by Vanuan** [comment] 2015-10-15 14:27
It's far better not to touch any code and fix the damn OS X rvm binary.

**Comment by crypticsymbols** [comment] 2015-10-15 15:41
I agree with @Vanuan, code was just a stopgap measure and the other approach is better.

**Comment by psk11** [comment] 2015-11-05 05:57
@Vanuan it does not worked for me

**Comment by Yenwod** [comment] 2015-11-18 17:17
Here is what worked for me:

I'm running OS X 10.11.1, Ruby 2.2.1, openssl 1.0.2d_1

Upgrading to Ruby 2.2.3 fixed the problem.

**Comment by dblommesteijn** [comment] 2016-01-08 10:28
A system wide solution would be this:

Downloading this http://curl.haxx.se/ca/cacert.pem, and saving it replacing `/usr/local/etc/openssl/cert.pem`. Add `export SSL_CERT_FILE=/usr/local/etc/openssl/cert.pem` to your `.bash_profile`. All net::http will pickup on `ENV['SSL_CERT_FILE']`.

**Comment by jb41** [comment] 2016-02-22 00:17
@dblommesteijn thank, works for me

**Comment by bgerd** [comment] 2016-03-10 20:31
@stevestofiel went with your fix thanks!

**Comment by katrusso** [comment] 2016-03-12 16:34
@dblommesteijn Thanks, this solution worked for me. :)

**Comment by flyfy1** [comment] 2016-03-29 07:47
Just in case anyone still facing issue.. upgrading to Ruby 2.3.0 helped me. (was in 2.2.3)

**Comment by schanami** [comment] 2016-03-29 20:39
Same issues here that everyone else went through.

I'm on El Capitan 10.11 and using version ruby 2.2.0

Tried the cert.pem replacement
Tried switching to 2.1.0 and 2.3.0
Tried: rvm osx-ssl-certs update all

What worked for me:
rvm reinstall 2.2.0 --disable-binary
gem pristine nokogiri --version 1.6.7.2

**Comment by mike0416** [comment] 2016-03-30 16:55
like @flyfy1 upgrading to Ruby 2.3.0 fixed the issue for me as well

**Comment by p55** [comment] 2016-03-31 00:10
upgrading ruby to 2.3.0 solved it for me as well

**Comment by aral** [comment] 2016-03-31 11:10
With rvm, on OS X, what fixed it for me was:

```bash
rvm reinstall 2.2.3 --disable-binary
```

(Replace with the version of Ruby you want to install as necessary.)

**Comment by arek-rst** [comment] 2016-04-11 09:54
@schanami helped me rvm reinstall 2.2.2 --disable-binary thx

**Comment by danebez** [comment] 2016-04-12 12:25
The solution for me on OS X 10.11.4, Ruby 2.1.2 was running `rvm reinstall ruby-2.1.2 --disable-binary` **or** switching to 2.3.0. This is perplexing as colleagues who had the app already set up on their dev machines and have the same OS and Ruby versions had this problem but could solve it in 2015 by simply downloading http://curl.haxx.se/ca/cacert.pem and ensuring that Ruby 2.1.2 was installed with the `--with-openssl-dir=$rvm_path/usr` flag. Can anyone can explain why installing Ruby from sources solves the problem?

To clarify, none of the following solved the issue:
- downloading http://curl.haxx.se/ca/cacert.pem, renaming it to cert.pem & pointing to it inside Rails (`ENV['SSL_CERT_FILE'] = '/usr/local/etc/openssl/cert.pem'`) or with a system environment variable
- running `rvm requirements`
- re-installing Ruby 2.1.2: `rvm remove 2.1.2 && rvm pkg install openssl && rvm install 2.1.2 --with-openssl-dir=$rvm_path/usr`

**Comment by Vanuan** [comment] 2016-04-12 15:04
> Can anyone can explain why installing Ruby from sources solves the problem?

Because pre-build version doesn't distinguish between different OS X versions (has wrong paths hardcoded). Newer OS X has a different SSL subsystem.

**Comment by sony-mathew-fd** [comment] 2016-05-17 05:58
Nice explanation given here : https://toadle.me/2015/04/16/fixing-failing-ssl-verification-with-rvm.html

**Comment by nchodelski** [comment] 2016-06-10 08:09
What worked for me with the error was:

`rvm reinstall 2.2.0 --disable-binary`
 then 
`rvm requirements`

none of the commands higher up this thread worked for some reason.

**Comment by kschutt** [comment] 2016-06-14 18:44
@nchodelski thanks! this also worked for me for `2.2.3`

**Comment by fenec** [comment] 2016-06-21 08:22
RVM > 1.9.1 comes with the method for updating certificates:  
`rvm osx-ssl-certs update all`

credits: http://railsapps.github.io/openssl-certificate-verify-failed.html

**Comment by dblommesteijn** [comment] 2016-06-22 15:07
@fenec this does not always solve the issue. I've given up fixing rvm and have switched to rbenv.

**Comment by nchodelski** [comment] 2016-06-22 17:40
I had some issues with this too. When i re installed a different version of
rvm I was able to build and deploy using fastlane (the reason I was trying
to fix my SSL errors in the first place). But it broke another feature for
me. and when i had managed to fix the second error I then had the SSL
authentication issue again. So seems like i can only choose one thing to
work.

I wish i knew what version to install to fix both errors at the same time.

**Comment by zegomesjf** [comment] 2016-06-24 00:13
I fix the error with
`rvm reinstall ruby-2.1.5 --with-openssl-dir=/usr/local`

**Comment by yossi-eynav** [comment] 2016-11-20 10:39
Thanks @zegomesjf!

**Closed** 2017-03-31 19:33 UTC
Labels: Priority: P2+, Status: Won't Fix, Type: Question

**Comment by georgemillo** [comment] 2017-06-26 16:36
I'm not using `google-api-ruby-client` but I just had this same Faraday error while trying to setup FB login with OAuth on my app, and found this issue. If any future Googlers see this, just writing this to confirm that `brew upgrade` and `brew upgrade openssl` worked me for too ;)

**Comment by spatle-drg** [comment] 2017-08-01 12:53
I have used in this way and it worked for me.
connection = Faraday.new("http://example.com")
connection.ssl.verify_mode = OpenSSL::SSL::VERIFY_NONE

**Comment by bryszard** [comment] 2017-09-20 10:19
Thank you @sony-mathew-fd. The solution pointed by you worked for me (https://toadle.me/2015/04/16/fixing-failing-ssl-verification-with-rvm.html).

I encountered this problem while I was using `google-cloud-ruby` gem and Ruby 2.4.0.

**Comment by brauliobo** [comment] 2017-09-21 13:25
Confirmed this problem with jruby 9.1.13.0

**Comment by vmardian** [comment] 2018-01-03 09:35
Using OS X 10.10.5 and Ruby 2.3.1 via RBENV, the issue was fixed by performing steps #2 and #3 from @bryszard's response.

**Comment by geordgez** [comment] 2018-06-01 14:43
FWIW switching to a different (open) wifi network may help. 

I'm no expert in networking/certificates but I recently ran into the same issue when I was trying to hit a Ruby backend with an OAuth callback. My environment was fine (macOS Sierra 10.12.6 + Docker Ruby 2.3.1 base image) and my local certificates were alright but the secured network I was on was modifying certificates to make it unfriendly for the Ruby app.

Just wanted to mention in case someone exhausted all the local options like me and was still getting:
```Faraday::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed)```

**Comment by MaximKurakin** [comment] 2024-07-16 09:31
> A system wide solution would be this (for Yosemite and Ruby 2.2.1):
> 
> Downloading this http://curl.haxx.se/ca/cacert.pem, and saving it replacing `/usr/local/etc/openssl/cert.pem`. Add `export SSL_CERT_FILE=/usr/local/etc/openssl/cert.pem` to your `.bash_profile`. All net::http will pickup on `ENV['SSL_CERT_FILE']`.
> 
> _RVM and ruby seems to have an outdated CA cert._

After 2 days of hell!!! Only this solutions worked for me. I successfully integrated openproject and nextcloud.
Thankyou!
