### ISSUE TITLE
Parsing JSON data from BigQuery takes a long time and eats a lot of memory

### ISSUE THREAD

**Issue by bittrance** [google/google-api-ruby-client#485] opened 2016-10-19 10:39 UTC
When switching a report job from 0.8 to 0.9, I noticed that the time it took to retrieve a BigQuery result set increased by more than 100%. We put queries that return fairly large result sets (~4M records) consisting of fairly short records of 6 columns for a total of about 100 bytes each, so the actual retrieval times matter. I decided to explore this difference; this issue is the report.

TL;DR BigqueryServiceV2#get_job_query_results takes 4x longer than curl + JSON#load() and consumes 50+ times more memory than result JSON string payload.

I wrote a test program that contains the same steps. Test program is a bit long to post here, see this gist https://gist.github.com/bittrance/91b6064e9a1a0091d6cba6bdd5e089f8, but the relevant episode looks like this:

``` ruby
logger.info("Putting first query")
partial = service.query_job(project_id, query_job, {})
job_id = partial.job_reference.job_id
logger.info("Result #{partial.total_rows} for #{job_id}")
while partial.page_token
  partial = service.get_job_query_results(
    project_id,
    job_id,
    page_token: partial.page_token
  )
  logger.info("Retrieved #{partial.rows.size} rows for #{job_id}")
end
```

Executing the above script on `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]` with a 2-core 2.7 GHz Intel Core i5 produces the following output. Looking at our production runs (on AWS Linux instances), it seems that the retrieval time for one batch of results is quite stable at 30 +/- 3 secs, so this is fairly representative:

```
I, [2016-10-19T08:36:12.887007 #87887]  INFO -- : Putting first query
I, [2016-10-19T08:38:37.437833 #87887]  INFO -- : Result 4196769 for job_X
I, [2016-10-19T08:39:03.836324 #87887]  INFO -- : Retrieved 58333 rows for job_X
I, [2016-10-19T08:39:32.235562 #87887]  INFO -- : Retrieved 58333 rows for job_X
...
```

I benchmarked this against a curl call by breaking the script between two batches and manually requesting the next batch. Thus:

``` bash
time curl -s -H 'Content-Type: application/json' -H 'Authorization: Bearer X' -X GET 'https://www.googleapis.com/bigquery/v2/projects/project_id/queries/job_X?pageToken=T' | wc
        6.93 real         0.08 user         0.14 sys
 1283390 1758700 12483416
```

As you can see from wc we are retrieving 12MiB of data, and it takes about 7 seconds. It thus seems that the driver takes at least 20 seconds to produce 58333 Ruby hashes out of the retrieved JSON, i.e. after it retrieved the data, before returning it.

As a reference, we can take the payload downloaded by curl and give it to JSON.load()

``` ruby
require 'benchmark'
require 'json'
Benchmark.measure { JSON.load(File.open('dump.json', 'rb')) }
=> #<Benchmark::Tms:0x007fbbac882b00 @label="", @real=0.6861894010216929, @cstime=0.0, @cutime=0.0, @stime=0.08, @utime=0.6100000000000001, @total=0.6900000000000001>
```

My conclusion would be that the API is about 30x slower than JSON.load() in parsing the returned data.

So who is wasting all my precious computrons? Asking ruby-prof 0.16.2 about it, it came up with this result. I have truncated it somewhat, but in short, representable creates ~4 objects per JSON item and makes tens of millions of Ruby calls to produce 758330 Ruby items.

```
Measure Mode: wall_time
Thread ID: 70326491019780
Fiber ID: 70326283488220
Total: 85.157908
Sort by: self_time

 %self      total      self      wait     child     calls  name
  7.58     24.575     6.452     0.000    18.123  2858541  *Class#new
  5.75      4.900     4.900     0.000     0.000 14351129   Representable::Definition#[]
  2.77      2.357     2.357     0.000     0.000     1204   <Class::Thread>#start
  2.72      3.902     2.319     0.000     1.583  4900424   Representable::Binding#[]
  2.68      2.284     2.284     0.000     0.000  1225060   Hash#initialize_copy
  2.56      5.466     2.178     0.000     3.287   817894   Kernel#dup
  2.50      4.420     2.133     0.000     2.287  1226273   Kernel#initialize_dup
  2.46      6.790     2.092     0.000     4.698   408376   Representable::Binding#initialize
  2.16      7.725     1.840     0.000     5.885  2041792   Uber::Options::Value#call
  1.68      2.563     1.431     0.000     1.132   408379   Hash#merge
  1.64      1.394     1.394     0.000     0.000   408370   Kernel#class
  1.58      1.867     1.343     0.000     0.524   408365   Enumerable#inject
  1.32      1.127     1.127     0.000     0.000  2800125   Kernel#block_given?
  1.23      1.046     1.046     0.000     0.000   408376   BasicObject#instance_exec
  1.15     13.918     0.978     0.000    12.940   408340   Enumerable#collect
  1.08      3.420     0.920     0.000     2.500   408340   Representable#representation_wrap
  1.04      5.193     0.886     0.000     4.308   816738   Uber::Options::Value#evaluate_for
  1.03      4.236     0.876     0.000     3.360   408340   Representable#normalize_options!
  0.87      2.164     0.738     0.000     1.427   816738   Representable::Binding#as
  0.84      6.481     0.712     0.000     5.769   408376   Representable::Mapper::Methods#skip_property?
  0.82      2.310     0.696     0.000     1.615   816680   Representable#representable_attrs
  0.81      0.691     0.691     0.000     0.000  2041792   Uber::Options::Value#dynamic?
  0.81      1.948     0.686     0.000     1.262   408376   Representable::Binding#update!
  0.79      0.674     0.674     0.000     0.000   816758   Hash#has_key?
  0.79      0.669     0.669     0.000     0.000        1   JSON::Ext::Parser#parse
  0.74      1.322     0.634     0.000     0.688   816752   Representable::Definition#typed?
  0.72      4.033     0.613     0.000     3.420   408340   Representable::Hash#filter_wrap
  0.69      9.093     0.589     0.000     8.504   408376   <Class::Representable::Hash::Binding>#build_for
  0.64      0.545     0.545     0.000     0.000   820344   Kernel#nil?
  0.63     12.940     0.539     0.000    12.401   408340   Representable::Config#each
  0.63      8.096     0.534     0.000     7.562   408339   Representable::Deserializer#create_object
  0.62      9.809     0.531     0.000     9.278   408376   <Class::Representable::Binding>#build
  0.62      1.461     0.526     0.000     0.935   408376   Representable::Definition#representable?
  0.61      3.076     0.522     0.000     2.554   408376   Representable::Hash::Binding#read
  0.60      2.888     0.513     0.000     2.375   350027  *Representable::Populator#deserialize
  0.56      4.025     0.480     0.000     3.545   408339   Representable::Deserializer::Prepare#prepare!
  0.56      0.702     0.477     0.000     0.225   408376   Representable::Definition#setter
  0.56      6.389     0.476     0.000     5.913   408339   Representable::Deserializer#class_for
  0.56      4.876     0.474     0.000     4.402   408376   Representable::Mapper::Methods#skip_conditional_property?
  0.54      0.775     0.460     0.000     0.314   816752   Representable::Definition#array?
  0.54      1.835     0.458     0.000     1.377   408376   Uber::Options::Value#proc!
  0.53     12.401     0.451     0.000    11.950   408340   Representable::Config::Definitions#each
  0.52      0.444     0.444     0.000     0.000   816699   Representable::Deserializer#initialize
  0.51     10.244     0.434     0.000     9.809   408376   Representable#representable_binding_for
  0.49      1.832     0.414     0.000     1.419   408376   Representable::Binding::Factories#populator
  0.49     16.032     0.414     0.000    15.618   408340   Representable#representable_mapper
  0.47      2.723     0.399     0.000     2.324   349998   Google::Apis::BigqueryV2::TableCell#initialize
  0.45      5.230     0.386     0.000     4.844   408339   Representable::Deserializer::Prepare#prepare
  0.45      1.521     0.382     0.000     1.139   408362   Representable::Binding::Factories#deserializer
  0.43     14.501     0.365     0.000    14.135   408340   Representable#representable_bindings_for
  0.43      1.457     0.365     0.000     1.092   408362   Representable::Binding#set
  0.43      0.364     0.364     0.000     0.000   408340   Representable::Decorator#initialize
  0.42      2.473     0.357     0.000     2.116   408362   Uber::Options::Value#callable!
  0.42      5.309     0.356     0.000     4.953   408362   Representable::Binding#parse_filter
  0.41      1.173     0.353     0.000     0.820   408339   Representable::Deserializer#instance_for
  0.40      0.695     0.344     0.000     0.350   408376   Representable::Mapper::Methods#skip_protected_property
  0.40      0.700     0.338     0.000     0.362   408376   Representable::Binding#setup_user_options!
  0.39      1.865     0.333     0.000     1.532   408339   Representable::Deserializer#class_from
  0.35      0.407     0.294     0.000     0.113   408340   Representable::Config#wrap_for
  0.35      1.674     0.294     0.000     1.380   408339   Representable::Binding#representer_module_for
  0.33      0.278     0.278     0.000     0.000   408376   Representable::Populator#initialize
  0.32      1.793     0.272     0.000     1.521   408362   Representable::Populator#deserializer
  0.32      0.553     0.269     0.000     0.284   408376   Representable::Definition#has_default?
  0.31      1.871     0.263     0.000     1.608   408339   Representable::Deserializer::Prepare#prepare_for
  0.29      2.116     0.249     0.000     1.866   408362   Representable::Pipeline#call
  0.29      0.562     0.246     0.000     0.316   408376   Representable::Binding#setup_exec_context!
  0.28      0.235     0.235     0.000     0.000   408340   Representable::Mapper::Methods#initialize
  0.27      3.202     0.234     0.000     2.968   408340   Representable::Mapper::Methods#bindings
  0.26      0.225     0.225     0.000     0.000   408376   String#intern
  0.26      0.221     0.221     0.000     0.000   408340   Representable::Declarative#representable_attrs
  0.26      0.218     0.218     0.000     0.000   408340   Hash#values
  0.25      0.217     0.217     0.000     0.000   408388   Hash#key?
  0.25      1.423     0.217     0.000     1.206   408337   Representable::Deserializer::Collection#item_deserializer
  0.25      1.608     0.212     0.000     1.395   408339   <Class::Representable::Decorator>#prepare
  0.24      0.327     0.205     0.000     0.122   350034   Representable::Definition#hash?
  0.24      0.386     0.200     0.000     0.185   349998   Google::Apis::BigqueryV2::TableCell#update!
  0.23      0.198     0.198     0.000     0.000   408376   Representable::Mapper::Methods#skip_excluded_property?
  0.21      0.178     0.178     0.000     0.000   408341   Hash#delete
  0.19      0.162     0.162     0.000     0.000   350093   String#==
  0.17      0.144     0.144     0.000     0.000   350027   Representable::Binding::Factories#deserializer_class
  0.16      0.139     0.139     0.000     0.000   350034   Representable::Binding::Factories#populator_class
  0.16      0.134     0.134     0.000     0.000   408339   Representable::Hash::Binding#deserialize_method
  0.16     77.131     0.133     0.000    76.998   758364  *Representable::Deserializer#call
  0.13      0.113     0.113     0.000     0.000   408340   Hash#[]
  0.09      0.478     0.078     0.000     0.400    58333   Google::Apis::BigqueryV2::TableRow#initialize
  0.09     74.843     0.076     0.000    74.768   408339  *Representable::Deserializer#demarshal
  0.08      0.068     0.068     0.000     0.000        1   OpenSSL::SSL::SSLSocket#connect
  0.07     75.021     0.060     0.000    74.960   408339  *Representable::Deserializer#deserialize
  0.07     77.438     0.059     0.000    77.379   408337  *Representable::Deserializer::Collection#deserialize!
...
```

The conclusion would be that if I used e.g. Hurley plus JSON.load(), fetching 4M records would take 500 seconds, while using google-api-client v 0.9 would take 2160 seconds, assuming that the HTTP request is of the same length.

I have also repeated the process with the v0.10 branch (that uses representable 3.0) but with the same result. Here follows a memory profiling (using memory_profiler 0.9.6):

```
allocated memory by location
-----------------------------------
1476620256  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable/binding.rb:46
1383710208  ~/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:81
 336003072  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable/pipeline.rb:39
 251584461  ~/.rbenv/versions/2.3.1/lib/ruby/2.3.0/json/common.rb:156
 235205280  ./vendor/bundle/ruby/2.3.0/gems/uber-0.0.15/lib/uber/options.rb:96
 206735520  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable.rb:67
  94734648  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable.rb:84
  32670080  ./vendor/bundle/ruby/2.3.0/gems/uber-0.0.15/lib/uber/options.rb:60
  32670080  ./vendor/bundle/ruby/2.3.0/gems/uber-0.0.15/lib/uber/options.rb:82
  32667200  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable.rb:69
  32667200  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable.rb:99
  32667200  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable/hash.rb:45
  32667120  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable/deserializer.rb:66
  27999840  ./vendor/bundle/ruby/2.3.0/bundler/gems/google-api-ruby-client-3d9bc4795993/generated/google/apis/bigquery_v2/classes.rb:2366
  24117329  ./vendor/bundle/ruby/2.3.0/gems/multi_json-1.11.0/lib/multi_json/adapters/json_common.rb:10
  16333560  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable/decorator.rb:11
  12530807  ./vendor/bundle/ruby/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:710
  12347872  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable/pipeline.rb:37
  11136150  ~/.rbenv/versions/2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:57

allocated memory by class
-----------------------------------
2127214256  Hash
1383330624  Thread
 335386176  Array
 218870776  Class
 198186361  String
  13999920  Google::Apis::BigqueryV2::TableCell
  13999920  Google::Apis::BigqueryV2::TableCell::Representation
   2333320  Google::Apis::BigqueryV2::TableRow
   2333320  Google::Apis::BigqueryV2::TableRow::Representation

allocated objects by gem
-----------------------------------
  11900581  representable-3.0.0
   2450220  uber-0.0.15
   1657723  2.3.1/lib

allocated objects by location
-----------------------------------
   6533720  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable/binding.rb:46
   1633420  ~/.rbenv/versions/2.3.1/lib/ruby/2.3.0/json/common.rb:156
    816752  ./vendor/bundle/ruby/2.3.0/gems/uber-0.0.15/lib/uber/options.rb:60
    816752  ./vendor/bundle/ruby/2.3.0/gems/uber-0.0.15/lib/uber/options.rb:82
    816716  ./vendor/bundle/ruby/2.3.0/gems/uber-0.0.15/lib/uber/options.rb:96
    816680  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable.rb:69
    816680  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable.rb:99
    816680  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable/hash.rb:45
    816678  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable/deserializer.rb:66
    816674  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable/pipeline.rb:39
    699996  ./vendor/bundle/ruby/2.3.0/bundler/gems/google-api-ruby-client-3d9bc4795993/generated/google/apis/bigquery_v2/classes.rb:2366
    408340  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable.rb:67
    408339  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable.rb:84
    408339  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable/decorator.rb:11
    116666  ./vendor/bundle/ruby/2.3.0/bundler/gems/google-api-ruby-client-3d9bc4795993/generated/google/apis/bigquery_v2/classes.rb:2727
     58335  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable/pipeline.rb:37

allocated objects by class
-----------------------------------
   7878400  Array
   6534920  Hash
   1180956  String
    408341  Class
    349998  Google::Apis::BigqueryV2::TableCell
    349998  Google::Apis::BigqueryV2::TableCell::Representation
     58333  Google::Apis::BigqueryV2::TableRow
     58333  Google::Apis::BigqueryV2::TableRow::Representation

retained memory by gem
-----------------------------------
 218870240  uber-0.0.15
  59153291  2.3.1/lib
  28682872  representable-3.0.0

retained memory by location
-----------------------------------
 218870240  ./vendor/bundle/ruby/2.3.0/gems/uber-0.0.15/lib/uber/options.rb:96
  59153211  ~/.rbenv/versions/2.3.1/lib/ruby/2.3.0/json/common.rb:156
  16333560  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable/deserializer.rb:66
  12347872  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable/pipeline.rb:37

retained memory by class
-----------------------------------
 218870240  Class
  59155335  String
  13999920  Google::Apis::BigqueryV2::TableCell
  12348672  Array
   2333320  Google::Apis::BigqueryV2::TableRow

retained objects by gem
-----------------------------------
    466688  representable-3.0.0
    408340  uber-0.0.15
    350021  2.3.1/lib

retained objects by location
-----------------------------------
    408340  ./vendor/bundle/ruby/2.3.0/gems/uber-0.0.15/lib/uber/options.rb:96
    408339  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable/deserializer.rb:66
    350019  ~/.rbenv/versions/2.3.1/lib/ruby/2.3.0/json/common.rb:156
     58335  ./vendor/bundle/ruby/2.3.0/gems/representable-3.0.0/lib/representable/pipeline.rb:37

retained objects by class
-----------------------------------
    408340  Class
    350061  String
    349998  Google::Apis::BigqueryV2::TableCell
     58351  Array
     58333  Google::Apis::BigqueryV2::TableRow
```

As can be seen, data consumption grows into hundreds of MiBs.
1. Is it possible to retrieve the unparsed HTTP body?
2. Is it reasonable that methods that can be expected to return large result sets consume so much resources? For me, the answer is no, I will have to do a workaround.

**Comment by sqrrrl** [comment] 2016-10-19 21:50
There's another feature request to allow using raw request/response bodies. I can add it, though I'd prefer to just speed up the main path. A little disappointed that representable 3.0 doesn't help.

Anyway, since it'll likely take a while to fix or replace representable, I'll take a look at adding an option to allow callers to handle serializing/deserializing bodies in 0.10

Short term workaround is use the `http` method on the service. It's not much more than calling the http client yourself, but does handle credentials, refreshing, retries, etc... but won't try and parse the body. Or if you're feeling adventurous you can monkey patch the service and define an alternate method that doesn't specify a response representation.

```ruby
module Google
  module Apis
    module BigqueryV2
      class BigqueryService
        def get_raw_job_query_results(project_id, job_id, max_results: nil, page_token: nil, start_index: nil, timeout_ms: nil, fields: nil, quota_user: nil, user_ip: nil, options: nil, &block)
          command =  make_simple_command(:get, 'projects/{projectId}/queries/{jobId}', options)
          command.params['projectId'] = project_id unless project_id.nil?
          command.params['jobId'] = job_id unless job_id.nil?
          command.query['maxResults'] = max_results unless max_results.nil?
          command.query['pageToken'] = page_token unless page_token.nil?
          command.query['startIndex'] = start_index unless start_index.nil?
          command.query['timeoutMs'] = timeout_ms unless timeout_ms.nil?
          command.query['fields'] = fields unless fields.nil?
          command.query['quotaUser'] = quota_user unless quota_user.nil?
          command.query['userIp'] = user_ip unless user_ip.nil?
          execute_or_queue_command(command, &block)
        end
      end
    end
  end
end
```

**Comment by sqrrrl** [comment] 2016-11-07 22:36
Closing as duplicate of #475

**Closed by sqrrrl** 2016-11-07 22:36 UTC
