### ISSUE TITLE
generate-api is looking for api_names_out.yaml but the name in the installed gem is api_names.yaml

### ISSUE THREAD

**Issue by rapind** [google/google-api-ruby-client#674] opened 2018-05-10 02:42 UTC
Just ran into this trying to generate from the texttospeech discovery doc (https://texttospeech.googleapis.com/$discovery/rest?version=v1beta1).

`generate-api gen api --file=discovery.json`

Results in the error:
`No such file or directory @ rb_sysopen - /Users/username/.rvm/gems/ruby-2.5.0/gems/google-api-client-0.20.1/api_names_out.yaml`

I was able to get it working by copying `/Users/username/.rvm/gems/ruby-2.5.0/gems/google-api-client-0.20.1/api_names_out.yaml` to `/Users/username/.rvm/gems/ruby-2.5.0/gems/google-api-client-0.20.1/api_names.yaml`

**Comment by mattwhisenhunt** [comment] 2018-05-10 20:52
Duplicate of #623

**Closed by mattwhisenhunt** 2018-05-10 20:52 UTC
